# Generated by Django 4.2.3 on 2024-02-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loader", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(null=True, upload_to="uploads")),
            ],
        ),
    ]
