# Generated by Django 4.2.3 on 2024-02-16 12:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("loader", "0002_uploadfiles"),
    ]

    operations = [
        migrations.RenameField(
            model_name="uploadfiles",
            old_name="file",
            new_name="file_to_upload",
        ),
    ]
