# Generated by Django 4.2.3 on 2024-02-16 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("loader", "0003_rename_file_uploadfiles_file_to_upload"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadfiles",
            name="to_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="upload_files",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
