# Generated by Django 4.2.9 on 2024-02-26 07:48

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("loader", "0007_alter_testmodel_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadfiles",
            name="db_record",
            field=model_utils.fields.StatusField(
                choices=[
                    ("НЕ ЗАПИСАНО В БД", "НЕ ЗАПИСАНО В БД"),
                    ("данные в базе", "данные в базе"),
                ],
                default="НЕ ЗАПИСАНО В БД",
                max_length=100,
                no_check_for_status=True,
            ),
        ),
    ]
