# Generated by Django 4.2.9 on 2024-02-28 06:04

from django.db import migrations, models
import loader.models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0010_testmodel_to_user_testmodel1_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfiles',
            name='db_record',
            field=model_utils.fields.StatusField(choices=[('draft', 'НЕ ЗАПИСАНО В БД'), ('published', 'данные в базе')], default='draft', max_length=100, no_check_for_status=True),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='file_to_upload',
            field=models.FileField(null=True, upload_to=loader.models.user_directory_path),
        ),
    ]
