# Generated by Django 4.2.3 on 2024-01-21 16:57

import django.contrib.auth.password_validation
import django.core.validators
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_user_email"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", users.models.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name="userextrafield",
            name="about_user",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="secret_email",
            field=models.EmailField(
                default=None, max_length=254, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="secret_login",
            field=models.CharField(
                default=None, max_length=128, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="secret_password",
            field=models.CharField(
                default=None,
                max_length=128,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(8),
                    django.contrib.auth.password_validation.validate_password,
                ],
            ),
        ),
    ]
