# Generated by Django 4.2.3 on 2024-01-22 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_user_managers_userextrafield_about_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="user_extra_field",
        ),
        migrations.AddField(
            model_name="userextrafield",
            name="user_extra_field",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
