# Generated by Django 4.2.3 on 2024-01-27 21:34

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_remove_user_user_extra_field_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="secret_login",
        ),
        migrations.AlterField(
            model_name="userextrafield",
            name="about_user",
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name="userextrafield",
            name="user_extra_field",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_extra_field",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
