# Generated by Django 4.2.3 on 2024-01-27 21:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_remove_user_secret_login_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userextrafield",
            old_name="user_extra_field",
            new_name="to_user",
        ),
    ]
