# Generated by Django 4.2.3 on 2024-01-31 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_rename_user_extra_field_userextrafield_to_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userextrafield",
            name="id",
        ),
        migrations.AlterField(
            model_name="userextrafield",
            name="to_user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="user_extra_field",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
