# Generated by Django 4.2.3 on 2023-07-18 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C', models.CharField(default=0, max_length=20)),
                ('Si', models.CharField(default=0, max_length=20)),
                ('Mn', models.CharField(default=0, max_length=20)),
                ('Cr', models.CharField(default=0, max_length=20)),
                ('Ni', models.CharField(default=0, max_length=20)),
                ('Ti', models.CharField(default=0, max_length=20)),
                ('Al', models.CharField(default=0, max_length=20)),
                ('W', models.CharField(default=0, max_length=20)),
                ('Mo', models.CharField(default=0, max_length=20)),
                ('Nb', models.CharField(default=0, max_length=20)),
                ('V', models.CharField(default=0, max_length=20)),
                ('S', models.CharField(default=0, max_length=20)),
                ('P', models.CharField(default=0, max_length=20)),
                ('Cu', models.CharField(default=0, max_length=20)),
                ('Co', models.CharField(default=0, max_length=20)),
                ('Zr', models.CharField(default=0, max_length=20)),
                ('Be', models.CharField(default=0, max_length=20)),
                ('Se', models.CharField(default=0, max_length=20)),
                ('N', models.CharField(default=0, max_length=20)),
                ('Pb', models.CharField(default=0, max_length=20)),
                ('Fe', models.CharField(default=0, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Metal_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(default=0)),
                ('date', models.DateTimeField(blank=True, verbose_name='date request')),
            ],
        ),
        migrations.CreateModel(
            name='Metal_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steel', models.CharField(blank=True, max_length=50)),
                ('steel_info', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('name_steel', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steel_name', to='metal.metal')),
                ('request_steel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steel_request', to='metal.metal_request')),
            ],
        ),
        migrations.CreateModel(
            name='Metal_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steel_class', models.CharField(blank=True, max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('chain_steel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steel_chain', to='metal.metal_info')),
            ],
        ),
    ]
