# Generated by Django 4.2.3 on 2023-08-01 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Metal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C', models.CharField(default=0, max_length=20)),
                ('Si', models.CharField(default=0, max_length=20)),
                ('Mn', models.CharField(default=0, max_length=20)),
                ('Cr', models.CharField(default=0, max_length=20)),
                ('Ni', models.CharField(default=0, max_length=20)),
                ('Ti', models.CharField(default=0, max_length=20)),
                ('Al', models.CharField(default=0, max_length=20)),
                ('W', models.CharField(default=0, max_length=20)),
                ('Mo', models.CharField(default=0, max_length=20)),
                ('Nb', models.CharField(default=0, max_length=20)),
                ('V', models.CharField(default=0, max_length=20)),
                ('S', models.CharField(default=0, max_length=20)),
                ('P', models.CharField(default=0, max_length=20)),
                ('Cu', models.CharField(default=0, max_length=20)),
                ('Co', models.CharField(default=0, max_length=20)),
                ('Zr', models.CharField(default=0, max_length=20)),
                ('Be', models.CharField(default=0, max_length=20)),
                ('Se', models.CharField(default=0, max_length=20)),
                ('N', models.CharField(default=0, max_length=20)),
                ('Pb', models.CharField(default=0, max_length=20)),
                ('Fe', models.CharField(default=0, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Metal_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steel_class', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Metal_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steel', models.CharField(blank=True, max_length=50, null=True)),
                ('steel_info', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('metals', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metal.metal')),
                ('metals_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metals_info', to='metal.metal_class')),
            ],
        ),
        migrations.CreateModel(
            name='MetalSearch',
            fields=[
                ('metal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='metal.metal')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
            bases=('metal.metal',),
        ),
        migrations.CreateModel(
            name='Metal_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(default=0)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('metals_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metals_request', to='metal.metal_info')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='metal_info',
            name='metalsearch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metals_info', to='metal.metalsearch'),
        ),
    ]
