# Generated by Django 4.2.3 on 2023-07-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metal_class',
            name='steel_class',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
