# Generated by Django 4.2.3 on 2023-07-19 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metal', '0002_alter_metal_class_steel_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metal_class',
            name='chain_steel',
        ),
        migrations.RemoveField(
            model_name='metal_info',
            name='name_steel',
        ),
        migrations.RemoveField(
            model_name='metal_info',
            name='request_steel',
        ),
        migrations.AddField(
            model_name='metal_info',
            name='metals',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metals_info', to='metal.metal'),
        ),
        migrations.AddField(
            model_name='metal_info',
            name='metals_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metals_info', to='metal.metal_class'),
        ),
        migrations.AddField(
            model_name='metal_request',
            name='metals_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metals_request', to='metal.metal_info'),
        ),
    ]
